### PR TITLE
Update to 0.4.post2

### PR DESCRIPTION
**Pull request by bletham**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

This upgrades to 0.4.post2.

It updates the recipe with some new formatting requirements for conda-build. The significant change is that it now skips build for [win and py27], because pystan skips build for that combination and pystan does not build. It also adds me as a maintainer.

### CODE REVIEW

**Comment by bletham** [comment]
Failure in build_linux_python3.7:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy=1.10 -> python=2.7
  - python=3.7
```

**Comment by bletham** [comment]
@rmax do you have any ideas about this windows build error? It's pretty opaque to me.

And is there any reason to not change the pinned numpy version to 1.11, since my understanding of the error above was that 1.10 is now only supported on py27?

**Comment by rmax** [comment]
@bletham I think the error comes from the selectors not working as expected with `py37` as `numpy 0.10` is not available for `py37`. The `0.10` was picked to use the older version available so it can work with any newer version.

Upgrading to `numpy 0.11` makes sense for `0.4`, IMO.

**Comment by bletham** [comment]
Cool, it looks like the windows error was transient since it passed this time, so once this last build finishes it should be good to go.

**Comment by rmax** [comment]
@bletham thank you!

**Pull request merged**
