### PR TITLE
Update version to 0.3.post2

### PR DESCRIPTION
**Pull request by rmax**

### CODE REVIEW

**Comment by brylie** [comment]
Ah, excellent. I just noticed this pull request. Will this be merged soon?

**Comment by brylie** [comment]
This would close issue #12

**Comment by rmax** [comment]
@brylie Thank you for your interest. 

We are waiting for a upstream release with the test fixes.

@bletham is there an ETA for the new release or can we backport the [patch](https://github.com/facebook/prophet/commit/a5869505c0b840a546d89c169763d36ef8414a4e) for conda users?

**Comment by bletham** [comment]
@rmax up now, as 0.3.post2

**Comment by bletham** [comment]
And just to be sure you saw my comment on the other PR, the model file location has moved to a single model at `fbprophet/stan_model/prophet_model.pkl`. This will need to be updated in the lines starting at https://github.com/conda-forge/fbprophet-feedstock/blob/master/recipe/meta.yaml#L24

**Comment by rmax** [comment]
@bletham Thanks. PR updated.

**Comment by bletham** [comment]
Awesome, thanks!

**Pull request merged**
