### PR TITLE
[new] Rebuild for Python 3.9 and 3.10

### PR DESCRIPTION
**Pull request by maresb**
Reviving #36

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@wardbrian, do you have any tips for how to make a legacy build of `fbprophet`? Or is it hopeless?

I seem to be getting weird dependency errors, I think connected with `pystan` being a py2.7 version.

```
- Encountered problems while solving:
-   - nothing provides toolchain_c_linux-64 needed by pystan-2.17.1.0-py27hf8a1672_3
```

or
```
nothing provides binutils_linux-64 2.31.1 h6176602_3 needed by gcc_linux-64-7.3.0-h553295d_3
```

**Comment by WardBrian** [comment]
I’m not sure about that specific error, but PyStan 2 was never supported on python 3.9 or later. This is part of what made upstream switch over entirely to cmdstanpy. 

Honestly, upstream should probably release a fbprophet 1.1 shim which is updated to point at prophet 1.1 or later

**Comment by maresb** [comment]
Giving up.

**Pull request closed without merging**
